// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalTestProject.Migrations
{
    [DbContext(typeof(UbysSystemDbContext))]
    [Migration("20240605210117_AddNewConvertedDefaultValuesToExams")]
    partial class AddNewConvertedDefaultValuesToExams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("FinalTestProject.Data.Danisman", b =>
                {
                    b.Property<long>("TCKimlikNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("TanimliOgrenciler")
                        .HasColumnType("TEXT");

                    b.Property<int>("UyelikType")
                        .HasColumnType("INTEGER");

                    b.HasKey("TCKimlikNo");

                    b.ToTable("Danisman");
                });

            modelBuilder.Entity("FinalTestProject.Data.Idareci", b =>
                {
                    b.Property<long>("TCKimlikNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcilanDersler")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<string>("DersListe")
                        .HasColumnType("TEXT");

                    b.Property<string>("OgretimElemaniList")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("UyelikType")
                        .HasColumnType("INTEGER");

                    b.HasKey("TCKimlikNo");

                    b.ToTable("Idareci");
                });

            modelBuilder.Entity("FinalTestProject.Data.Ogrenci", b =>
                {
                    b.Property<long>("TCKimlikNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Donem")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OgrenciDanismani")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecilmisDersler")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Sinif")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UyelikType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Yariyil")
                        .HasColumnType("INTEGER");

                    b.HasKey("TCKimlikNo");

                    b.HasIndex("OgrenciDanismani");

                    b.ToTable("Ogrenci");
                });

            modelBuilder.Entity("FinalTestProject.Data.OgretimElemani", b =>
                {
                    b.Property<long>("TCKimlikNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecilmisDersler")
                        .HasColumnType("TEXT");

                    b.Property<int>("UyelikType")
                        .HasColumnType("INTEGER");

                    b.HasKey("TCKimlikNo");

                    b.ToTable("OgretimElemani");
                });

            modelBuilder.Entity("FinalTestProject.Models.Ders", b =>
                {
                    b.Property<string>("DersKodu")
                        .HasColumnType("TEXT");

                    b.Property<float>("AKTS")
                        .HasColumnType("REAL");

                    b.Property<string>("DersAdi")
                        .HasColumnType("TEXT");

                    b.Property<float>("Kredi")
                        .HasColumnType("REAL");

                    b.Property<string>("OgrenciList")
                        .HasColumnType("TEXT");

                    b.Property<long?>("OgretimElemaniTc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaatCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Yariyil")
                        .HasColumnType("INTEGER");

                    b.HasKey("DersKodu");

                    b.HasIndex("OgretimElemaniTc");

                    b.ToTable("Ders");
                });

            modelBuilder.Entity("FinalTestProject.Models.DersNotu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DersKodu")
                        .HasColumnType("TEXT");

                    b.Property<int>("HarfNotu")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OgrenciTc")
                        .HasColumnType("INTEGER");

                    b.Property<float>("SonucNotu")
                        .HasColumnType("REAL");

                    b.Property<int>("YoklamaDurumu")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DersKodu");

                    b.HasIndex("OgrenciTc");

                    b.ToTable("DersNotu");
                });

            modelBuilder.Entity("FinalTestProject.Models.DersSecimi", b =>
                {
                    b.Property<long>("OgrenciKimlikNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DanismanKimlikNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecilenDersler")
                        .HasColumnType("TEXT");

                    b.HasKey("OgrenciKimlikNo");

                    b.ToTable("DersSecimi");
                });

            modelBuilder.Entity("FinalTestProject.Models.SecilenDers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DersKodu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TcKimlikNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DersKodu");

                    b.HasIndex("TcKimlikNo");

                    b.ToTable("SecilenDers");
                });

            modelBuilder.Entity("FinalTestProject.Data.Ogrenci", b =>
                {
                    b.HasOne("FinalTestProject.Data.Danisman", "OgrDanisman")
                        .WithMany()
                        .HasForeignKey("OgrenciDanismani");

                    b.Navigation("OgrDanisman");
                });

            modelBuilder.Entity("FinalTestProject.Models.Ders", b =>
                {
                    b.HasOne("FinalTestProject.Data.OgretimElemani", "OgretimElemani")
                        .WithMany()
                        .HasForeignKey("OgretimElemaniTc");

                    b.Navigation("OgretimElemani");
                });

            modelBuilder.Entity("FinalTestProject.Models.DersNotu", b =>
                {
                    b.HasOne("FinalTestProject.Models.Ders", "Ders")
                        .WithMany()
                        .HasForeignKey("DersKodu")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinalTestProject.Data.Ogrenci", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciTc")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("FinalTestProject.Models.Sinav", "AraSinav", b1 =>
                        {
                            b1.Property<int>("DersNotuId")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("ogr_not")
                                .HasColumnType("REAL")
                                .HasColumnName("AraSinavNot");

                            b1.Property<float>("yuzde")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("REAL")
                                .HasDefaultValue(40f)
                                .HasColumnName("AraSinavYuzde");

                            b1.HasKey("DersNotuId");

                            b1.ToTable("DersNotu");

                            b1.WithOwner()
                                .HasForeignKey("DersNotuId");
                        });

                    b.OwnsOne("FinalTestProject.Models.Sinav", "FinalSinav", b1 =>
                        {
                            b1.Property<int>("DersNotuId")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("ogr_not")
                                .HasColumnType("REAL")
                                .HasColumnName("FinalSinavNot");

                            b1.Property<float>("yuzde")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("REAL")
                                .HasDefaultValue(60f)
                                .HasColumnName("FinalSinavYuzde");

                            b1.HasKey("DersNotuId");

                            b1.ToTable("DersNotu");

                            b1.WithOwner()
                                .HasForeignKey("DersNotuId");
                        });

                    b.Navigation("AraSinav");

                    b.Navigation("Ders");

                    b.Navigation("FinalSinav");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("FinalTestProject.Models.SecilenDers", b =>
                {
                    b.HasOne("FinalTestProject.Models.Ders", null)
                        .WithMany()
                        .HasForeignKey("DersKodu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalTestProject.Models.DersSecimi", null)
                        .WithMany()
                        .HasForeignKey("TcKimlikNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
