// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalTestProject.Migrations
{
    [DbContext(typeof(UbysSystemDbContext))]
    [Migration("20240601172540_UpdateCreate")]
    partial class UpdateCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("FinalTestProject.Data.Danisman", b =>
                {
                    b.Property<long>("TCKimlikNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("TanimliOgrenciler")
                        .HasColumnType("TEXT");

                    b.Property<int>("UyelikType")
                        .HasColumnType("INTEGER");

                    b.HasKey("TCKimlikNo");

                    b.ToTable("Danisman");
                });

            modelBuilder.Entity("FinalTestProject.Data.Idareci", b =>
                {
                    b.Property<long>("TCKimlikNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcilanDersler")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<string>("DersListe")
                        .HasColumnType("TEXT");

                    b.Property<string>("OgretimElemaniList")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("UyelikType")
                        .HasColumnType("INTEGER");

                    b.HasKey("TCKimlikNo");

                    b.ToTable("Idareci");
                });

            modelBuilder.Entity("FinalTestProject.Data.Ogrenci", b =>
                {
                    b.Property<long>("TCKimlikNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Donem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OgrenciDanismani")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecilmisDersler")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Sinif")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UyelikType")
                        .HasColumnType("INTEGER");

                    b.HasKey("TCKimlikNo");

                    b.ToTable("Ogrenci");
                });

            modelBuilder.Entity("FinalTestProject.Data.OgretimElemani", b =>
                {
                    b.Property<long>("TCKimlikNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecilmisDersler")
                        .HasColumnType("TEXT");

                    b.Property<int>("UyelikType")
                        .HasColumnType("INTEGER");

                    b.HasKey("TCKimlikNo");

                    b.ToTable("OgretimElemani");
                });

            modelBuilder.Entity("FinalTestProject.Models.Ders", b =>
                {
                    b.Property<string>("DersKodu")
                        .HasColumnType("TEXT");

                    b.Property<float>("AKTS")
                        .HasColumnType("REAL");

                    b.Property<string>("DersAdi")
                        .HasColumnType("TEXT");

                    b.Property<float>("Kredi")
                        .HasColumnType("REAL");

                    b.Property<string>("OgrenciList")
                        .HasColumnType("TEXT");

                    b.Property<int>("SaatCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Yariyil")
                        .HasColumnType("INTEGER");

                    b.HasKey("DersKodu");

                    b.ToTable("Ders");
                });

            modelBuilder.Entity("FinalTestProject.Models.DersNotu", b =>
                {
                    b.Property<long?>("OgrenciTCKimlikNo")
                        .HasColumnType("INTEGER");

                    b.HasIndex("OgrenciTCKimlikNo");

                    b.ToTable("DersNotu");
                });

            modelBuilder.Entity("FinalTestProject.Models.DersNotu", b =>
                {
                    b.HasOne("FinalTestProject.Data.Ogrenci", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciTCKimlikNo");

                    b.Navigation("Ogrenci");
                });
#pragma warning restore 612, 618
        }
    }
}
